server:
  port: 8762

spring:
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER_URI:https://vollify.eu.auth0.com/}

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

auth0:
  audience: http://localhost:8761/data-sevice

# Logging
logging:
  level:
    org:
      springframework:
        security: TRACE