server:
  port: 8762

spring:
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${KEYCLOAK_URL:http://localhost:8080}/realms/edge-service-realm

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'