server:
  port: 8761

spring:
  cloud:
    gateway:
      default-filters:
        - name: Retry
          args:
            retries: 15
            backoff:
              firstBackoff: 50ms
              maxBackoff: 500ms
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    gateway:
      enabled: true
    web:
      exposure:
        include: '*'
