server:
  port: 8761


spring:
  main:
    web-application-type: reactive
  session:
    store-type: redis
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}

  cloud:
    gateway:
      default-filters:
        - name: Retry
          args:
            retries: 15
            backoff:
              firstBackoff: 50ms
              maxBackoff: 500ms
        - name: TokenRelay
        - name: SaveSession

      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${OAUTH2_ISSUER_URI:http://localhost:8080}/realms/edge-service-realm
        registration:
          keycloak:
            provider: keycloak
            clientId: ${OAUTH2_CLIENT_ID}
            clientSecret: ${OAUTH2_CLIENT_SECRET}
            scope:
              - openid
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    gateway:
      enabled: true
    web:
      exposure:
        include: '*'

logging:
  level:
    org:
      springframework:
        security: DEBUG