version: "3.8"

volumes:
  postgres-data:
  keycloak-data:

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  keycloak:
    image: quay.io/keycloak/keycloak
    container_name: "keycloak"
    command:
      - start-dev --import-realm
    volumes:
      - ./platform/keycloak:/opt/keycloak/data/import
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=changeit

    ports:
      - '8080:8080'


  zipkin-server:
    image: openzipkin/zipkin
    container_name: zipkin-server
    ports:
      - '9411:9411'