version: "3.5"

networks:
  backend:
    name: backend
    driver: bridge

volumes:
  postgres_data:
    driver: local

services:
  config-service:
    image: ghcr.io/volalm15/config-service:latest
    container_name: config-service
    restart: unless-stopped
    env_file:
      - prod.env
    networks:
      - backend
    ports:
      - "8760:8760"

  discovery-service:
    image: ghcr.io/volalm15/discovery-service:latest
    container_name: discovery-service
    restart: unless-stopped
    env_file:
      - prod.env
    networks:
      - backend
    ports:
      - "8888:8888"
  edge-service:
    image: ghcr.io/volalm15/edge-service:latest
    container_name: edge-service
    restart: unless-stopped
    env_file:
      - prod.env
    networks:
      - backend
    ports:
      - "8761:8761"
    depends_on:
    - keycloak
    - redis

  data-service:
    image: ghcr.io/volalm15/data-service:latest
    restart: unless-stopped
    env_file:
      - prod.env
    networks:
      - backend
    ports:
      - "8000-8020:8762"
    deploy:
      mode: replicated
      replicas: 2

  redis:
    image: redis
    restart: unless-stopped
    command: [ "redis-server", "--protected-mode", "no" ]
    env_file:
      - prod.env
    networks:
      - backend
    ports:
      - "6379:6379"

  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    env_file:
      - prod.env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${KEYCLOAK_POSTGRES_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}

  keycloak:
    image: quay.io/keycloak/keycloak
    container_name: keycloak
    hostname: keycloak
    restart: unless-stopped
    command: start --db=postgres
    env_file:
      - prod.env
    networks:
      - backend
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak
      KC_DB_USERNAME: ${KEYCLOAK_POSTGRES_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}
      KC_DB_SCHEMA: public

      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HOSTNAME_STRICT: false
      KC_HTTP_ENABLED: true

      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}

    ports:
      - "8080:8080"
    depends_on:
      -   postgres