version: "3.8"

networks:
  backend:
    name: backend
    driver: bridge

volumes:
  postgres_data:
    driver: local

services:
  config-service:
    image: ghcr.io/volalm15/config-service:latest
    container_name: config-service
    env_file:
      - prod.env
    networks:
      - backend

  discovery-service:
    image: ghcr.io/volalm15/discovery-service:latest
    container_name: discovery-service
    env_file:
      - prod.env
    networks:
      - backend
    ports:
      - "8888:8888"

  edge-service:
    image: ghcr.io/volalm15/edge-service:latest
    container_name: edge-service
    env_file:
      - prod.env
    networks:
      - backend
    ports:
      - "8761:8761"
    depends_on:
    - keycloak
    - redis

  data-service:
    image: ghcr.io/volalm15/data-service:latest
    env_file:
      - prod.env
    networks:
      - backend
    ports:
      - "8000-8020:8762"
    deploy:
      mode: replicated
      replicas: 2

  redis:
    image: redis
    container_name: redis
    env_file:
      - prod.env
    networks:
      - backend
    ports:
      - "6379:6379"

  postgres:
    image: postgres
    container_name: postgres
    env_file:
      - prod.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${KEYCLOAK_POSTGRES_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}

  keycloak:
    image: quay.io/keycloak/keycloak
    container_name: keycloak
    env_file:
      - prod.env
    command: start-dev
    networks:
      - backend
    environment:
      DB_ADDR: postgres
      DB_VENDOR: postgres
      DB_USER: ${KEYCLOAK_POSTGRES_USER}
      DB_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      -   postgres