server:
  port: 8762

spring:
  zipkin:
    base-url: http://zipkin-server:9411
  sleuth:
    sampler:
      probability: 1.0
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER_URI:http://localhost:8080}/realms/${OAUTH2_REALM:edge-service-realm}

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'