server:
  port: 8761


spring:
  session:
    store-type: redis
  redis:
    host: ${REDIS_HOST:redis}
    port: ${REDIS_PORT:6379}

  cloud:
    gateway:
      default-filters:
        - name: Retry
          args:
            retries: 15
            backoff:
              firstBackoff: 50ms
              maxBackoff: 500ms
        - name: TokenRelay

      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

  security:
    oauth2:
      client:
        provider:
          auth0:
            issuer-uri: ${OAUTH2_ISSUER_URI}
        registration:
          auth0:
            provider: auth0
            clientId: ${OAUTH2_CLIENT_ID}
            clientSecret: ${OAUTH2_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    gateway:
      enabled: true
    web:
      exposure:
        include: '*'
