version: "3.8"

volumes:
  postgres_data:
    driver: local
services:

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: changeit

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak
    command: start-dev
    environment:
      DB_ADDR: postgres
      DB_VENDOR: postgres
      DB_USER: admin
      DB_PASSWORD: changeit
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: changeit
    ports:
      - "8080:8080"
    depends_on:
      -   postgres