server:
  port: 8760

spring:
  zipkin:
    base-url: http://zipkin-server:9411
  sleuth:
    sampler:
      probability: 1.0
  application:
    name: config-service
  profiles:
    active: ${APP_PROFILE:native}
  cloud:
    config:
      server:
        native:
          search-locations:
            - classpath:/config
        git:
          uri: https://github.com/volalm15/app
          search-paths: 'config/'
eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8888/eureka/}
  instance:
    lease-expiration-duration-in-seconds: ${DISCOVERY_LEASE_EXPIRATION:3}
    lease-renewal-interval-in-seconds: ${DISCOVERY_LEASE_RENEWAL:1}
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${random.value}

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
