name: Build config-service
on:
  push:
    branches: [ main ]
    paths:
      - "config-service/**"
  pull_request:
    branches: [ main ]
    paths:
      - "config-service/**"
      
permissions:
  contents: read
  
jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run gradle build
        run: ./gradlew :config-service:bootJar
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build docker image
        run: docker build --build-arg JAR_FILE=config-service/build/libs/*.jar -t vollify/config-service:latest -f config-service/Dockerfile .
        
      - name: Build the hello-world Docker image
        run: |
          docker push ghcr.io/vollify/config-service:latest
          
      - uses: actions/upload-artifact@v2
        with:
          path: config-service/build/libs/*.jar
