name: Build data-service
on:
  push:
    branches: [ main ]
    paths:
      - "data-service/**"
  pull_request:
    branches: [ main ]
    paths:
      - "data-service/**"
      
permissions:
  contents: read
  
jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run gradle build
        run: ./gradlew :data-service:build

      - uses: actions/upload-artifact@v2
        with:
          path: data-service/build/libs/*.jar
